services:

    # Needed for core
    postgres:
        image: postgres:16.6
        container_name: hyvor_postgres
        restart: always
        environment:
            POSTGRES_USER: hyvor
            POSTGRES_PASSWORD: hyvorpw
            POSTGRES_MULTIPLE_DATABASES: hyvor
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./pgsql-multidb:/docker-entrypoint-initdb.d

volumes:
    postgres_data: