#!/bin/sh

set -e

mkcert -key-file meta/traefik/hyvor.dev.key.pem -cert-file meta/traefik/hyvor.dev.pem hyvor.dev
mkcert -key-file meta/traefik/wildcard.hyvor.dev.key.pem -cert-file meta/traefik/wildcard.hyvor.dev.pem "*.hyvor.dev"