#!/bin/sh

set -e

# Generate SSL certificates
echo "Generating SSL certificates..."
mkcert -key-file meta/compose/traefik/hyvor.dev.key.pem -cert-file meta/compose/traefik/hyvor.dev.pem hyvor.dev
mkcert -key-file meta/compose/traefik/wildcard.hyvor.dev.key.pem -cert-file meta/compose/traefik/wildcard.hyvor.dev.pem "*.hyvor.dev"

# Create docker network if not exists
echo "Creating docker network..."
docker network inspect hyvor-network >/dev/null 2>&1 || docker network create hyvor-network

# Create data directories
echo "Creating data directories..."
mkdir -p data/minio data/mailpit data/postgres

components = "core talk blogs"

# Minio buckets
echo "Creating Minio buckets..."
# create dir in data/minio for each
for bucket in $components; do
  mkdir -p data/minio/$bucket
done
