#!/bin/sh

set -e

# Generate SSL certificates
echo "Generating SSL certificates..."
mkcert -key-file meta/compose/traefik/hyvor.localhost.key.pem -cert-file meta/compose/traefik/hyvor.localhost.pem hyvor.localhost
mkcert -key-file meta/compose/traefik/wildcard.hyvor.localhost.key.pem -cert-file meta/compose/traefik/wildcard.hyvor.localhost.pem "*.hyvor.localhost"

# Create docker network if not exists
echo "Creating docker network..."
docker network inspect hyvor-network >/dev/null 2>&1 || docker network create hyvor-network

# Create data directories
echo "Creating data directories..."
mkdir -p data/minio data/mailpit data/postgres

components="core talk blogs post relay agora"

# Minio buckets
echo "Creating Minio buckets..."
# create dir in data/minio for each
for bucket in $components; do
  mkdir -p data/minio/$bucket
done
