#!/bin/sh

# Usage: ./run <component>
# Example: ./run core

set -x

component=$1

if [ -z "$component" ]; then
  echo "Component name is required. Usage: ./run <component>"
  exit 1
fi

if [ ! -d "$component" ]; then
  echo "Component $component does not exist."
  exit 1
fi

# Sync internal library
echo "Syncing internal library"
rsync -avz --exclude 'vendor' internal $component/backend/packages

# Watch internal library for changes
if command -v fswatch &> /dev/null
then
  echo "Using fswatch to sync internal library"
  fswatch -o internal | xargs -I{} rsync -avzq --exclude 'vendor' internal $component/backend/packages &
  FS_WATCH_PID=$!
else
  echo "NOTICE: fswatch is not available. Please install fswatch to sync internal library"
fi

cleanup() {
  echo "Cleaning up"
  # kil all child processes
  pkill -P $$  --signal 9
  rm -rf $component/backend/packages/internal
}

trap cleanup INT

# Run compose
PROFILE=${2:-dev}
echo "Running $component with profile $PROFILE"
docker compose  -f $component/compose.yaml --profile $PROFILE up --build --watch

cleanup