apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
data:
  DB_HOST: pgsql-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: hyvor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  labels:
    component: core
spec:
  replicas: 2
  selector:
    matchLabels:
      component: core
  template:
    metadata:
      labels:
        component: core
    spec:
      containers:
        - name: core
          image: hyvorcoreminikube:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: core-config

---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  labels:
    component: core
spec:
  selector:
    component: core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
