[[tls.certificates]]
certFile = "/etc/traefik/hyvor.localhost.pem"
keyFile = "/etc/traefik/hyvor.localhost.key.pem"

[[tls.certificates]]
certFile = "/etc/traefik/wildcard.hyvor.localhost.pem"
keyFile = "/etc/traefik/wildcard.hyvor.localhost.key.pem"

[http.middlewares]
[http.middlewares.vite-retry.retry]
attempts = 5
initialInterval = "100ms"
