apiVersion: v1
kind: ConfigMap
metadata:
    name: core-env
data:
    HYVOR_INSTANCE: "https://{{ .Values.instance.domain }}"
    
    DB_HOST: {{ .Values.instance.db.host }}
    DB_PORT: {{ .Values.instance.db.port }}
    DB_USER: {{ .Values.instance.db.user }}
    DB_PASSWORD: {{ .Values.instance.db.password }}
    DB_DATABASE: {{ .Values.components.core.db.database }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: core-deployment
    labels:
        component: core
    spec:
        containers:
            - name: core
              image: hyvor/core:0.0.30
              ports:
                  - containerPort: 3000
              envFrom:
                  - configMapRef:
                        name: core-config

---
apiVersion: v1
kind: Service
metadata:
    name: core-service
    labels:
        component: core
spec:
    selector:
        component: core
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: ClusterIP
