# pgsql

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgsql-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: hyvor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
  labels:
    component: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pgsql
  template:
    metadata:
      labels:
        component: pgsql
    spec:
      containers:
        - name: pgsql
          image: postgres:16.6
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pgsql-config

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
  labels:
    component: pgsql
spec:
  selector:
    component: pgsql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
