apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://hyvor-service-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST