{
 "title": "API",
 "description": "App HTTP API metrics ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "label": "Component", "query": { "query": "label_values(component)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({component=\"$component\", job=\"app_api\"},instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values({component=\"$component\"},endpoint)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values({component=\"$component\"},status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total Requests in the selected period",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(app_api_http_requests_total{component=~\"$component\",endpoint=~\"$endpoint\",instance=~\"$instance\",status=~\"$status\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(floor(sum by(endpoint) (increase(app_api_http_requests_total{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$__range]))))",
     "legendFormat": "Endpoint"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum(max_over_time(app_api_http_requests_total{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$__range])- min_over_time(app_api_http_requests_total{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$__range])) by (status))",
     "legendFormat": "Endpoint"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Per second rate",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_api_http_requests_total{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "500 Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(app_api_http_requests_total{component=~\"$component\",instance=~\"$instance\",status=\"500\"}[$__range])))",
     "legendFormat": "Count"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(app_api_http_request_duration_seconds_bucket{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slow Endpoints",
   "type": "table",
   "description": "These are the slowest endpoints on average",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(increase(app_api_http_request_duration_seconds_sum{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$__range])) by (endpoint)\n    /\n    clamp_min(sum(increase(app_api_http_request_duration_seconds_count{component=~\"$component\",instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$__range])) by (endpoint), 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}