# Configure the cluster (which services to install)
cluster:
    # Whether to create a PGSQL database within the cluster
    # Set this to false if you are using an external database like AWS RDS
    db: true

instance:
    # The primary domain of the instance
    # This is where you will be hosting the HYVOR Instance
    # Each component (product) is accessible via https://{component}.{domain}
    # Required
    domain: "hyvor.example.org"

    # The app key for the instance
    # Always use HTTPS for production
    https: true

    # This is used to encrypt communication between components
    # and also to generate tokens for authentication, etc.
    # Required
    appKey: ""

    # This is used to enable/disable debug mode
    # Keep false in production
    appDebug: false

    # The PostgreSQL Database
    # If cluster.db is true, you can use the default values
    db:
        host: "pgsql-service"
        port: "5432"
        user: "postgres"
        password: "postgres"

    # Mail Configuration (SMTP)
    mail:
        host: ""
        port: ""
        user: ""
        password: ""
        from: ""
        name: ""

    # S3 Storage for media files
    # You can use any S3 compatible storage like AWS S3, Minio, etc.
    s3:
        accessKeyID: ""
        secretAccessKey: ""
        bucket: ""
        pathStyle: false

# Configure the components (products) to install
components:
    # Core Component
    # This is the main component that handles the core functionality
    # including authentication and other central services
    core:
        db:
            # name of the database
            database: hyvor

    # Hyvor Talk (talk.hyvor.com)
    # Commenting Platform
    talk:
        enabled: true

    # TODO: ...
